# Generated by Django 2.1.7 on 2020-03-20 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('release_date', models.TextField()),
                ('poster_path', models.TextField()),
                ('overview', models.TextField()),
                ('imdb_rating', models.FloatField(default=0.0)),
                ('imdb_votes', models.IntegerField(default=0)),
                ('imdb_id', models.TextField()),
                ('metascore', models.IntegerField(default=0)),
                ('rt_rating', models.IntegerField(default=0)),
                ('certification', models.TextField()),
                ('runtime', models.TextField()),
                ('genre', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
