# Generated by Django 2.1.7 on 2020-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fortune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
