# Generated by Django 2.1.7 on 2020-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fortune', '0003_movienotfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='movienotfound',
            name='tmdb_popularity',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='movienotfound',
            name='tmdb_rating',
            field=models.IntegerField(default=-1),
        ),
    ]
