# Generated by Django 2.1.7 on 2020-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fortune', '0004_auto_20200325_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienotfound',
            name='tmdb_rating',
            field=models.FloatField(default=-1),
        ),
    ]
