# Generated by Django 2.1.7 on 2020-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fortune', '0005_auto_20200325_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_documentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_standup',
            field=models.BooleanField(default=False),
        ),
    ]
