# Generated by Django 2.1.7 on 2020-03-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fortune', '0006_auto_20200331_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_documentary',
            new_name='documentary',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='is_standup',
            new_name='standup',
        ),
    ]
